name: Deploy Hugo Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Ls -R
      run: |
        pwd
        ls -R ./

    - name: Build
      run: hugo build --config ./hugo-site/hugo.yaml --buildDrafts --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./

    - name: Move subdirectory contents to root
      run: |
        shopt -s dotglob
        rm -f index.html
        mv ./hugo-site/public/* .
        rm -rf hugo-site

