name: Deploy Hugo Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Remote all web content 
      run: |
        rm -f *
        rm -rf ./public
        rm -rf ./hugo-site

    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        sparse-checkout: 'hugo-site'  # specify the subdirectory to checkout
        sparse-checkout-cone-mode: false

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Ls -R
      run: |
        mv -f ./hugo-site/* ./
        pwd
        ls -al

    - name: GC
      run: hugo --gc --config ./hugo.yaml

    - name: Build
      run: hugo --config ./hugo.yaml --buildDrafts --ignoreCache --enableGitInfo --minify

    - name: Hugo
      run: hugo --config ./hugo.yaml

    - name: Move subdirectory contents to root
      run: |
        shopt -s dotglob
        mv ./public ..
        rm -rf ./*
        mv -f ../public/ .
        mv -f ./public/* .../../../
        rmdir ./public

